In [12]:
import tensorflow as tf
import numpy as np
import random

[RNN(tensorflow.ver)]
tensorflow에서 제공하는 일반적인 RNN layers
- 기본 RNN : tf.keras.layers.SimpleRNN
- LSTM : tf.keras.layers.LSTM
- GRU : tf.keras.layers.GRU

기본적인 tensor shape : [batch, timesteps, feature]


In [11]:
# tf.keras.SimpleRNN 실습
# 1. input data의 shape 설정하기
sequence_len = 16
feature_dim = 32
input_sequence = tf.keras.Input(shape = (sequence_len,feature_dim))

print(input_sequence[0:3])

units = 64               # 은닉층 내의 계산에 필요한 노드의 개수

# 2. 모델 객체 생성하기
simpleRNN = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units),
    tf.keras.layers.Dense(4,activation = 'softmax')
])

# 3. 생성한 inputdata를 RNN에 넣어주기
simpleRNN(input_sequence)
simpleRNN.summary()

# (+) RNN layer를 여러 층 쌓을 때 return_sequences = True가 꼭 필요하다.
rnn = tf.keras.Sequential([
    tf.keras.layers.SimpleRNN(units,return_sequences=True),
    tf.keras.layers.SimpleRNN(units,return_sequences=True),
    tf.keras.layers.SimpleRNN(units),
    tf.keras.layers.Dense(4,activation = 'softmax')

])

rnn(input_sequence)
rnn.summary()


KerasTensor(type_spec=TensorSpec(shape=(None, 16, 32), dtype=tf.float32, name=None), name='tf.__operators__.getitem_5/strided_slice:0', description="created by layer 'tf.__operators__.getitem_5'")
Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_9 (SimpleRNN)     (None, 64)                6208      
_________________________________________________________________
dense_7 (Dense)              (None, 4)                 260       
Total params: 6,468
Trainable params: 6,468
Non-trainable params: 0
_________________________________________________________________
Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
simple_rnn_10 (SimpleRNN)    (None, 16, 64)            6208      
_________________________________________________________________
simple_rnn_11 (SimpleRNN)    (N

In [18]:
# tensorflow 공식문서에 있는 예제 실습

# 1. input data 설정
inputs = np.random.random([32,10,8]).astype(np.float32)
print(inputs[0])
simple_rnn = tf.keras.layers.SimpleRNN(4)

output = simple_rnn(inputs)

# 2. 모델 객체 생성
simple_rnn = tf.keras.layers.SimpleRNN(
    4, return_sequences = True, return_state = True
)

# 3. 모델 학습
whole_sequence_output, final_state = simple_rnn(inputs)
print(simple_rnn(inputs))


[[0.91913307 0.6538851  0.40834615 0.52895117 0.20793532 0.5196509
  0.41469848 0.6684876 ]
 [0.5348182  0.32958293 0.47733015 0.7365685  0.51901174 0.7245719
  0.47548586 0.21680012]
 [0.71873176 0.2515378  0.20301442 0.01355956 0.6987435  0.25670996
  0.01112409 0.46451432]
 [0.82648927 0.44578156 0.42941967 0.22714475 0.74694777 0.7054632
  0.74405223 0.5350035 ]
 [0.8202502  0.9505462  0.5945084  0.32007092 0.76203924 0.05417415
  0.28965768 0.10499713]
 [0.6469576  0.6282116  0.10215176 0.84706646 0.18780267 0.9479964
  0.8316178  0.3460667 ]
 [0.7806944  0.22428416 0.5092722  0.43582097 0.20391534 0.62834454
  0.72947174 0.17291303]
 [0.67214465 0.8539699  0.2078268  0.3087864  0.37848392 0.99173135
  0.10831729 0.9402645 ]
 [0.31366062 0.73908156 0.83056784 0.68753093 0.29741064 0.63722306
  0.7037061  0.7298062 ]
 [0.3300683  0.35273647 0.01675337 0.8080716  0.64206123 0.8495237
  0.64649117 0.9390194 ]]
[<tf.Tensor: shape=(32, 10, 4), dtype=float32, numpy=
array([[[-0.57042724

In [26]:
# tensorflow SimpleRNN 실습 - (2)
# 1. 임의의 입력 데이터 생성하기
train_X = [[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]
print(np.shape(train_X))  # 단어의 벡터 차원은 5이고, 문장의 길이는 => 즉 4번의 시점이 존재

train_X = [[[0.1, 4.2, 1.5, 1.1, 2.8], [1.0, 3.1, 2.5, 0.7, 1.1], [0.3, 2.1, 1.5, 2.1, 0.1], [2.2, 1.4, 0.5, 0.9, 1.1]]]
train_X = np.array(train_X, dtype = np.float32)

print(train_X.shape)

# 2. 모델 객체 생성
rnn2 = tf.keras.layers.SimpleRNN(3)
hidden_state = rnn2(train_X)

print('hidden state : {}, shape : {}'.format(hidden_state, hidden_state.shape))

rnn3 = tf.keras.layers.SimpleRNN(3, return_sequences = True)
hidden_state2 = rnn3(train_X)


# (+) return_sequences와 return_state
# 1. return_sequences = True 
print('hidden state : {}, shape : {}'.format(hidden_state2, hidden_state2.shape))
# reqeunces_sequences = True : 모든 시점에 대해서 은닉상태의 값을 출력하므로 (1,4,3)크기의 텐서 출력

# 2. return_state = True 
rnn4 = tf.keras.layers.SimpleRNN(3, return_sequences=True, return_state=True)
hidden_states3, last_state3 = rnn4(train_X)

print('hidden states : {}, shape: {}'.format(hidden_states3, hidden_states3.shape))
print('last hidden state : {}, shape: {}'.format(last_state3, last_state3.shape))

(4, 5)
(1, 4, 5)
hidden state : [[ 0.11190259  0.7635743  -0.7383125 ]], shape : (1, 3)
hidden state : [[[-0.99982095  0.99990684 -0.9928325 ]
  [-0.9963161   0.9901295  -0.9945824 ]
  [ 0.07190195  0.9255673  -0.9006116 ]
  [-0.96646833 -0.31942895 -0.79504144]]], shape : (1, 4, 3)
hidden states : [[[-0.37950125 -0.99998146  0.8538579 ]
  [-0.90090996 -0.99509317  0.40671185]
  [-0.1903357  -0.97840416  0.93146   ]
  [-0.9228084  -0.3114125  -0.7664354 ]]], shape: (1, 4, 3)
last hidden state : [[-0.9228084 -0.3114125 -0.7664354]], shape: (1, 3)


In [33]:
# 심화) LSTM 실습

lstm = tf.keras.Sequential([
    tf.keras.layers.LSTM(units),
    tf.keras.layers.Dense(4, activation = 'softmax')
])  

lstm(input_sequence)
lstm.summary()

# (+) return_state = True로 설정하면 LSTM의 마지막 cell state와 hidden state를 모두 return
# tf.keras.Sequential에서는 각 layer의 output이 1개일때만 사용가능

# LSTM 클래스에 tf.keras.Model을 상속
class LSTM(tf.keras.Model):
    def __init__(self):
        super(LSTM,self).__init__()
        self.lstm_layer = tf.keras.layers.LSTM(units, return_sequences = True, return_state = True)
        self.dense = tf.keras.layers.Dense(4, activation = 'softmax')

    def call(self, inputs):
        whole_seq_output,final_hidden_state, final_cell_state = self.lstm_layer(inputs)

        # shape를 출력
        print("whole_seq_ouput : ", whole_seq_output.shape)
        print("final_hidden_state : ", final_hidden_state.shape)
        print("final_cell_state : ",final_cell_state.shape)

        output_prob = self.dense(whole_seq_output)
        return output_prob

lstm = LSTM()
lstm(input_sequence)




Model: "sequential_15"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_8 (LSTM)                (None, 64)                24832     
_________________________________________________________________
dense_16 (Dense)             (None, 4)                 260       
Total params: 25,092
Trainable params: 25,092
Non-trainable params: 0
_________________________________________________________________
whole_seq_ouput :  (None, 16, 64)
final_hidden_state :  (None, 64)
final_cell_state :  (None, 64)


<KerasTensor: shape=(None, 16, 4) dtype=float32 (created by layer 'lstm_9')>

In [ ]:
# 심화2 ) GRU 실습